/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Lock } from "./Lock";
export type { MyToken } from "./MyToken";
export type { StampNFT } from "./StampNFT";
export type { StamplyRegistry } from "./StamplyRegistry";
